<?php

namespace AppBundle\Repository;

/**
 * persoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class persoRepository extends \Doctrine\ORM\EntityRepository
{
}
